return {
	style: require "cord.wim.style"
	stylesheet: require "cord.wim.stylesheet"
	node: require "cord.wim.node"
	container: require "cord.wim.container"
	widget: require "cord.wim.widget"
	layout: require "cord.wim.layout"
	animation: require "cord.wim.animation"
	animator: require "cord.wim.animator"
	textbox: require "cord.wim.textbox"
	imagebox: require "cord.wim.imagebox"
	nodebox: require "cord.wim.nodebox"
	screen: require "cord.wim.screen"
	trait: require "cord.wim.trait"
}
